Organic_Launch/Controllers/FarmController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Organic_Launch.Controllers
{
    public class FarmController : Controller
    {
        private FarmSaleDBEntities db = new FarmSaleDBEntities();
        // GET: Farmer
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            return View(db.Products.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Edit(int id)
        {
            return View(db.Farms.Where(i => i.farmID == id).FirstOrDefault());
        }

        [HttpPost]
        public ActionResult Edit()
        {
            return View();
        }

        public ActionResult Delete()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            db.Farms.Remove(db.Farms.Where(i => i.farmID == id).FirstOrDefault());
            return View();
        }
    }
}

Organic_Launch/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Organic_Launch.Controllers
{
    public class ProductController : Controller
    {
        private FarmSaleDBEntities db = new FarmSaleDBEntities();
        // GET: Product
        public ActionResult Single(int id)
        {
            return View(db.Products.Where(x => x.productID == id).FirstOrDefault());
        }

        public ActionResult List()
        {
            return View(db.Products.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Edit()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Edit(int id)
        {
            return View();
        }

        public ActionResult Delete()
        {
            return View();
        }
    }
}

Organic_Launch/Views/Product/List.cshtml
@model IEnumerable<Organic_Launch.Product>

@{
    ViewBag.Title = "List";
}


    <h2>Farmer's Page</h2>
    @foreach (var item in Model)
    {

        <div class="col-sm-4">
            <a href="@Url.Action("Single", "Product", new { id = item.productID})" id="@item.productID">
                <img src="img/img.jpg" alt="@item.productName" />
            </a>
            <ul>
                <li>@Html.DisplayFor(modelItem => item.productName)</li>
                <li>@Html.DisplayFor(modelItem => item.price)</li>
                <li>@Html.DisplayFor(modelItem => item.productCategory)</li>
                <li>@Html.DisplayFor(modelItem => item.productDescription)</li>
            </ul>
            <div>
                <a href="@Url.Action("Edit", "Farm", new { id = item.productID})" id="@item.productID">Edit</a>
                <a href="@Url.Action("Delete", "Farm")" id="@item.productID">Delete</a>
            </div>
        </div>
    }

Organic_Launch/Views/Product/Single.cshtml
@model Organic_Launch.Product

@{
    ViewBag.Title = "Single";
}

<h2>Single</h2>

<section>
    <h4>Product</h4>
    <hr />
    <div class="col-sm-6">
        <img src="" alt="@Model.productName" />
    </div>

    <div class="col-sm-6">
            <p>
                @Html.DisplayFor(model => model.productName)
            </p>
            <p>
                @Html.DisplayFor(model => model.price)
            </p>
            <p>
                @Html.DisplayFor(model => model.productCategory)
            </p>
            <p>
                @Html.DisplayFor(model => model.productDescription)
            </p>
    </div>
    
</section>